### ISSUE TITLE
Design Recognition Certificate for contributors

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/curriculum-localization#2]
We plan to provide digital certificates to all contributors of this campaign as a form of recognition and gratitude for their effort.

I'm still unclear on what content should go into this. Maybe we have done this before and have something to guide us?

I think we want to mention that they participated in the November campaign and contributed to localizing curriculum. @acabunoc, @xmatthewx and @secretrobotron would love your input on what content to add.

Rizwan stated that the contributors for this campaign likely fall into the Emerging Leaders membership tier so it would be nice if the content and design also implied that implicitly.

Again, we can talk more about this during a call I will set up for discussing the incentive designs.

cc @hannahkane

**Comment by abbycabs** [comment]
@auremoser made these for our first Open Leadership Cohort

![screen shot 2016-06-06 at 5 26 10 pm](https://cloud.githubusercontent.com/assets/617994/20072187/6ce7eb92-a4f5-11e6-97e6-304f09b1dfdd.png)

Do you have info on how much / how long people contributed?

**Comment by auremoser** [comment]
:) we can make new certificates. We also made "themed" foxes for each of the fellows for their discipline, so instead of science fox/research fox, we had geo-fox, etymology-fox, etcet. 

The foxes can be [found here](https://www.dropbox.com/sh/5vdulenagw8r4jy/AACuQjSsRdLSh-CQhOW7rMyCa?dl=0), you can print them (`.png` files), sent them as stickers to contributors, or modify the template to have the science fox holding other things relevant to these contributors (`.ai` files). It's a lot more work but it would be really cute!

![map-fox](https://cloud.githubusercontent.com/assets/1559703/20073012/90d4ba5a-a4f8-11e6-9b15-63754f40f2d7.png)

**Comment by natalieworth** [comment]
These are adorable!

**Comment by flukeout** [comment]
Oh nice!

**Comment by gideonthomas** [comment]
It would be awesome if we can somehow incorporate this into https://github.com/mozilla/curriculum-localization/issues/1. As for the certificate I think that's a great approach (making it friendly and playful). I'm not super familiar with what our recognition program dictates in terms of formality of the certificate, maybe @hannahkane or @simonwex might know?

**Comment by hannahkane** [comment]
I don't think we've established any standards for certificates. @xmatthewx might want to weigh in on this, but I'd be okay treating this as a one-off.

The OLC certificate is cute. @flukeout designed one for [Club Captains](https://github.com/mozilla/learning.mozilla.org/issues/1849#issuecomment-222023623), which looks fairly professional, so that's another possible model.

**Comment by hannahkane** [comment]
@sabrinang - wondering if this is on your radar for this heartbeat? (Sorry, I'm a bit out of the loop.)

**Comment by sabrinang** [comment]
@hannahkane Yeah, I chatted with @gideonthomas on Thursday and I believe this comes after poster and sticker incentives so it is on the radar since these deliverables should be finished by end of the month to be delivered on time.

**Comment by gideonthomas** [comment]
@hannahkane would love to talk about this sometime this week if you're available

**Comment by hannahkane** [comment]
@gideonthomas - can you provide a brief agenda for this? Wondering if it needs face-to-face chat or if we can discuss here? My schedule this week is very up in the air.

**Comment by gideonthomas** [comment]
@sabrinang and @hannahkane I think we should stick to a more formal type of certificate for this, similar to the Club Captains certificate. The important thing would be to clarify language in the certificate (I will talk to comms people) and make it a little more unique from the Club Captains cert.
