### ISSUE TITLE
Visual (& Communication) Direction for Curriculum Localization Campaign

### ISSUE THREAD

**Issue by sabrinang** [mozilla/curriculum-localization#4]
The campaign doesn't have visuals for the incentive assets so we need to figure out what we want it to represent and what it looks like.

#### Context Links:
Website: https://mozilla.github.io/curriculum-localization
Campaign Proposal (November 2016 - "Offline Icebreakers"): https://docs.google.com/document/d/127BUYvXmtwFvWXoFb85sB9Vq_m3X8xKB279dNEOv-Z4/edit?pli=1#

#### Themes to Represent:
- Localization
- Community
- Teach the Web
- Leadership

#### Campaign Assets Include:
- Poster *(for print)*
- Sticker *(for print)*
- Certificate *(digital)*
- The website can also use the visuals their too

There were some questions and discussion topics that were brought up and we need to figure out.
- **Content:** what content does the assets need? (campaign name? customized to their language? no text just illustrative? MLN visuals?) what copy does it need? (campaign tagline, mozilla mission statement, i contributed.. etc.)
- **Communication/Marketing:** who are these coming from and how do we want to position our messaging in the assets that it is meaningful? how is the campaign communicated and represented on these assets? (from the l10n teaching curriculum campaign, the mozilla learning network or mozilla?)
- **Locales/Languages:** which locales should we consider when designing? do we design them in English or avoid text? (around 10 locales)
- **Audience:** how does the l10n curriculum community want to be represented (educators that happen to speak another language or as localizers first?)

#### Visual Ideas:
I'll start by brainstorming a direction (i.e abstract patterns, photography, animals etc.) that isn't locale specific and a direction that ties into existing [Mozilla Learning Network](https://learning.mozilla.org/en-US/) visuals that are more generic and evergreen to look aligned with out other efforts. Since MLN presence will be revised next year and this is for a small audience, @xmatthewx suggested to keep the scope small to avoid complexity. 

/cc @gideonthomas @hannahkane

**Comment by xmatthewx** [comment]
This is thorough and thoughtful, and the scope seems big and could become 10 days of work. With the MLN web presence on our plate, and the need for a UI toolkit to speed up our work, I think we need to narrow this down to a single, small, easy deliverable. 

A few hours on a nice poster can have big impact to help catalyze the campaign. Two weeks on unique graphics for a suite of assets does not seem likely to have ten-times more impact. I might be mistaken, too unfamiliar with the campaign, but let's discuss before we proceed.

I recommend we do a simple poster, use it, learn from it, and then iterate on it later.

**Comment by hannahkane** [comment]
Agree with @xmatthewx that we should keep this a small task. Though it's important, it will likely affect a small number of (awesome) volunteers.

I believe we've promised a certificate, but I think we can just adapt the language on the Club Captain certificate.

For a poster content, it would be fantastic if we can find a creative way to either not have words, or to do something in the spirit of the MozFest materials where we said "One ______ Web" and let people fill in the blank with a localized word. I would focus on localization as the theme (as opposed to localizing curriculum), so that it can be applied to a number of different calls-to-action.

**Comment by gideonthomas** [comment]
+1 to keeping it simple. I wasn't aware of a revision of the MLN presence next year so I agree that it totally makes sense to limit the scope of this.

I'm a little concerned about focussing on localization as the theme because we really haven't done enough research to inform how that would translate into assets, text, graphics, etc. that will be part of the poster. I don't know if trying to create something generic to suit all locales would be problematic or not, so I'm going to follow @secretrobotron's advice and talk to someone who is more experienced with localization tomorrow. This will help us figure out what theme we should focus on (I agree with @hannahkane that focusing on 1 will simplify things).

@sabrinang going to brainstorm a bit to give you some input about your questions and will try to keep it as simple as possible.

**Comment by hannahkane** [comment]
Just putting a note here so I don't forget later: @gideonthomas has convinced me that curriculum might be a better theme than localization. Delighted to refer to people with more experience on this issue.

**Comment by sabrinang** [comment]
I played around with the community line art and colour (from https://learning.mozilla.org/en-US/community) if we are going with a localization theme (I know Hannah pointed out curriculum may be the better theme but this was an exploration from earlier today). 

The poster features the inverted line art (some icons such as the globe, translate and map markers can be simply swapped out to make it more curriculum-y themed) and we could think about translating text and using photography from their region. This could be a simple approach that matches some of the visual aesthetics of [learning.mozilla.org](learning.mozilla.org).
<img width="1341" alt="screen shot 2016-11-15 at 4 37 18 pm" src="https://cloud.githubusercontent.com/assets/2492510/20330273/6d2dadb8-ab52-11e6-8276-0ab2edd1a365.png">

**Comment by gideonthomas** [comment]
@sabrinang These look great, I like the art/icons used! After talking to @TheoChevalier, figuring out assets that represent localization is actually hard so the instinct was to not include them. However, your current design does it really well by circumventing the need for a specific asset to represent l10n (here are some examples of what they are currently working with: https://twitter.com/DelphineLebedel/status/750768575409905664 and https://twitter.com/DelphineLebedel/status/751719439448494080).

I really like the idea of photography from their region, but do you think that will be easy to acquire (who would acquire it). If it is challenging, I don't think it's a bad idea to just stick to a single background for all, but I'll leave it to your judgement.

As for text, we may want to just have "mozilla l10n" be the text shown since it doesn't need to be localized into different languages so that might keep it simple.

If you think that having it be curriculum-themed might be easier (purely from a design perspective), I would still lean towards that. Using dapper fox isn't a bad idea (again, only if it is easy) but once concern that was brought up was that people shouldn't be confused that this is in any way related to Firefox. If you feel that might happen, we should nix the fox.

One pending question I have that maybe @hannahkane might be able to answer better is: who are these incentives coming from? (from the l10n teaching curriculum campaign, the mozilla learning network or mozilla?)

@sabrinang I would say go with the simplest option since we can always revisit some of these questions next year when we have a clearer understanding of how we're going to approach these campaigns (and incentives) in the future. 

Let me know if I can help in any way until then and let me know what you think!

**Comment by hannahkane** [comment]
+1 to all of @gideonthomas's comments. To answer the question about who this is coming from, I would say Mozilla, but would like @xmatthewx to weigh in on that as well.

**Comment by sabrinang** [comment]
Chatted with @gideonthomas earlier about:

#### Visual Direction

We liked using a central graphic with the line art but the line art needs to reflect curriculum/education more so I’ll be working on replacing some iconography seen but keeping the community line art central. We will just have the mozilla wordmark present with no text to avoid localization complications and for it being to l10n specific. When the central graphic/wordmark layout is established, I can work in photography but this will be left until later on in the campaign when we know which ones to do. I can experiment with the colours to follow and how they work with the photography and how it would print.

#### Printing Logistics

For stickers, we most likely will get them done by sticker mule but the smallest quantity order is 50. https://www.stickermule.com/ca/custom-stickers. Depending on format, it should run about $60-$75 for 50 stickers. We can design the sticker that works for all then (no custom treatments).

For posters, we should figure out which printer we are going with and decide where these ship to if we are sending them out to each location. We should decide what dimension this poster should be so we can figure out how to best ship them (i.e. rolled in tube? folded with cardboard in envelope so it doesn’t bend?) When we figure out where we should print this, we can get a quote on ~20 unique posters to see how much it costs (if the budget is tight, we may need to consider printing quantities of 1 design which may same on cost)

**Comment by hannahkane** [comment]
cc @simonwex

**Comment by sabrinang** [comment]
https://redpen.io/p/ng9042fe442b5b3b45

I've updated the line art to be more curriculum/education themed than localization. The mozilla wordmark is incorporated in the sticker/poster. The poster features a different composition of line art than the sticker. I tried various colours for stickers but one photo example shown so far until locales are known.

**Comment by hannahkane** [comment]
Really liking these, @sabrinang! If I had to choose, I'd go with the light blue or pink for the stickers. What do others think?

**Comment by gideonthomas** [comment]
@sabrinang, these are amazing! I can provide the list of locales tomorrow since I'm closing the signup form then as well. I personally like the purple, magenta or gradient stickers.

**Comment by sabrinang** [comment]
@gideonthomas Informed me we will print swag with https://www.theprintful.com/ and here are some apparel ideas using the designs we have:

![apparel_mockups](https://cloud.githubusercontent.com/assets/2492510/21441346/7709da70-c84c-11e6-83a7-dc4d8fb85f85.png)

I like the vneck for shirts (the circular necklines always seem so high up and tight) and should consider unisex cuts if we have female contributors or female style shirts too. Tank tops or totes could be a fun option and I included some ideas for alternatives if needed. Also they have some all-over print options we can do some fun stuff with printing to the edge for the non-circular design.

I will export the two design vectors so they can be shared out in case I don't have time to continue this in January.

**Comment by hannahkane** [comment]
@gideonthomas - can you help us to re-engage on this issue? Do we need @xmatthewx to approve the design work?

**Comment by gideonthomas** [comment]
Sure!

I think we should probably stick to this T-shirt: https://www.theprintful.com/custom/items-for-all-over-printing/86/american-apparel-pl401-sublimation-t-shirt?tab=Info

### The things left to do
- Pick one line art design
- Pick one background
- Upload final asset here
  - We should follow the guidelines mentioned under the "Print Guidelines" section of the website above.

### My Opinion
For the sake of simplicity, I think we shouldn't have different backgrounds for each locale (as we originally wanted). Instead, I do really like the gradient background used in the tank-top above. If we can pick the colors for that and use the same line art used in that tank, I think that should suffice for all the T-shirts we print.

@hannahkane would like to hear your thoughts on this too!

---

From what I understand about the current situation, we already have the line art assets. I guess all that needs to be done is a background needs to be created (after choosing one) and then combined and uploaded here according to the guidelines from the T-shirt website.

One other thing I would like is the certificate asset! If I can be given the certificate/template, I can edit the content in it instead of taking up more design time (assuming this is possible). I intend to keep the design almost identical (to the one we use for clubs).

This is slightly urgent (I'm really sorry for the lack of coordination). I plan to send out the email to the contributors asking about their addresses and sizes for shipping this week. So it would be good to have this design work done this week or early next week so that I can place the order soon.

@xmatthewx and @sabrinang any help with this would be greatly appreciated!

**Comment by hannahkane** [comment]
I second your opinion; the gradient is really nice on the shirt.

**Comment by hannahkane** [comment]
@sabrinang - would you be able to get us the line art assets by early next week, by chance?

**Comment by sabrinang** [comment]
I have an .ai file here with all 3 designs: https://drive.google.com/file/d/0B4Q8pzCpDS_eeFZMQWNXSEFCQ0k/view
<img width="1153" alt="screen shot 2017-01-11 at 10 36 30 am" src="https://cloud.githubusercontent.com/assets/2492510/21861475/d9e17eee-d7e9-11e6-972b-ba412228fda3.png">
For the first design with the extended lines, Luke gave me feedback saying that the dotted line may feel like its pointing at ones crotch so I'd be a bit unsure of that particular design for a shirt application if people interpret it that way lol.

.jpgs are in the folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eY2FzZzkzWl9ITnc

**Comment by gideonthomas** [comment]
@sabrinang awesome! Thanks! Would you be able to provide the certificate file as well?
