### ISSUE TITLE
Does spanish localization is still in need?

### ISSUE THREAD

**Issue by lasr21** [mozilla/curriculum-localization#6]
Hi, I just see the page and I wonder if all the kits are already localized in spanish or some are still orphans.

**Comment by gideonthomas** [comment]
Hi @lasr21, I apologize for the delayed response, I don't seem to be getting notifications from this repository.

Although the campaign is over, we will always be happy to welcome translations for other languages, in this case Spanish since it hasn't been localized in that locale yet. If you do feel like your community can benefit from the Offline Icebreakers activities being translated in Spanish, feel free to go ahead and get started at your leisure. The website will still be up and the activities will still be accessible to localize.

If you have any questions, please do not hesitate to reach out to me in this issue thread.
